version: '3.3'

services:
   sqlserver:
     image: sierracsd/mocksifdb:1.2
     container_name: "sqlserver"
     ports:
      - "1433:1433"
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Qwerty2020"

   sif:
     depends_on:
       - sqlserver
     image: sierracsd/sifapisandbox:1.2
     container_name: "sif"
     ports:
       - "8080:80"
       - "3443:443"
